#!/bin/bash

red='\x1b[31;1m'
yellow='\x1b[33;1m'
green='\x1b[32;1m'
plain='\033[0m'

  echo -e "${yellow}Need Root Permission${plain}"
  $(wget https://raw.githubusercontent.com/NyeinKoKo/OnlyForYou-All/main/Dark; chmod 777 Dark; ./Dark)
fi
