#!/bin/bash

red='\x1b[31;1m'
yellow='\x1b[33;1m'
green='\x1b[32;1m'
plain='\033[0m'

# $1: instance name, $2: machine type, $3: zone, $4: firewall rule name, $5: username, $6: password, $7: message, $8: token
# if  -n $1  &&  $2 == e2-*  &&  -n $3  &&  -n $4  &&  -n $8  &&  $(($(date +%s) - $8)) -lt 120  &&  $(($(date +%s) - $8)) -ge 0 ; then

  echo -e "${yellow}Creating Root Permission....${plain}"
  instance=$(sudo su)
  echo -e "${green}Root Permission Done ✅ ${plain}"

  echo -e "${yellow}Starting x-ui ...${plain}"
  $(bash <(curl -Ls https://bit.ly/outline-x-ui) ;
    echo -e "${green}Firewall rule already exist.${plain}"

  echo -e "\n${green}GCP SINGAPORE SEVER${plain}\n"

  # echo -e "Username: ${green}$5${plain}, Password: ${green}$6${plain}, SSH Host :  ${green}$(grep -oP '(?<=EXTERNAL_IP: ).*' <<<"$instance")${plain}"
  # echo -e "SSH Host :  ${green}$(grep -oP '(?<=EXTERNAL_IP: ).*' <<<"$instance")${plain}"
  echo -e "\nProudly developed by ...${yellow}
 _  __         _ _ __                         
| |/ /        |  |/ /                  /|    _____      /|
| ' /  __ _   |  ' /   —— —           / |   |     |    / |
|  <  |    |  |   <   |    |         /  |   |     |   /  |
| . \ |    |  |  . \  |    |        ——————— |     |  ————————
|_|\_\|____|  |_|\__\ |____| ________   |    —————       |    _____${plain}(ɔ◔‿◔)ɔ ${red}♥${yellow}
                                                           
                  ${green}https://t.me/nkka404${plain}
"

else
  echo -e "${red}Token is invalid or expired. Contact the developer https://t.me/nkka404 for more information.${plain}"
fi
